#                                  Saptaswa Basu
        
# Top 5 unique Numpy functions with varieties of work 


### The functions is useful in many cases to perform unique operations with the major intension to reduce mathematical calculations.

Numpy is a Python library that provides a multidimensional array object. Below we are going to discussed about some of the functions that are often used to solve various problems.

- np.greater_equal
- np.split
- np.transpose
- np.unique
- np.extract


In [14]:
!pip install jovian --upgrade -q

In [15]:
import jovian

In [8]:
jovian.commit(project='numpy-array-assignment')

<IPython.core.display.Javascript object>

[jovian] Updating notebook "saptaswabasu00/numpy-array-assignment" on https://jovian.ai
[jovian] Committed successfully! https://jovian.ai/saptaswabasu00/numpy-array-assignment


'https://jovian.ai/saptaswabasu00/numpy-array-assignment'

Let's begin by importing Numpy and listing out the functions covered in this notebook.

In [1]:
import numpy as np

In [2]:
# List of functions explained 
function1 = np.greater_equal  
function2 = np.split
function3 = np.transpose
function4 = np.unique
function5 = np.extract

## Function 1 - np.greater_equal 

This function is used to make comparison between two arrays to get boolean values as a output. Here if one index value is greater than the other its gives true and vice-versa.

In [12]:
# Example 1 - working (change this)
arr1 = [[1, 2], 
        [3, 4.]]

arr2 = [[5, 9],
        [1, 1]]

arr3 = [[5, 6, 7], 
        [8, 9, 10]]

arr4 = [[9, 6, 3],
        [8, 6, 4]]

np.greater_equal(arr1,arr2)

array([[False, False],
       [ True,  True]])

In example 1 shows the working of greater_equal function , as compared to arr1 and arr2 the 1st and 2nd index value in second row of arr1 is greater, so as a result at those position output shows as True.

In [11]:
# Example 2 - working
np.greater_equal(arr3,arr4)

array([[False,  True,  True],
       [ True,  True,  True]])

Here also shown the same operation but with 3*3 array where 5 index value of arr3 is greater than that of arr4 , so there as a output boolean value True is printed.

In [13]:
# Example 3 - breaking (to illustrate when it breaks)
arr1 = [[1, 2], 
        [3, 4.]]

arr2 = [[5, 6, 7], 
        [8, 9, 10]]

np.greater_equal(arr1,arr2)

ValueError: operands could not be broadcast together with shapes (2,2) (2,3) 

In this example we worked with two arrays with different shapes, one is 2x2 and another is 3x3 in shapes. And according to numpy functions , its only applicable when both the array have same shapes.

To fix this issue we can either make arr1 as 3x3 or arr2 as 2x2 , so both of them have same shapes , that helps numpy to execute the operations properly.

In [4]:
jovian.commit()

<IPython.core.display.Javascript object>

[jovian] Updating notebook "saptaswabasu00/numpy-array-operations" on https://jovian.ai
[jovian] Committed successfully! https://jovian.ai/saptaswabasu00/numpy-array-operations


'https://jovian.ai/saptaswabasu00/numpy-array-operations'

## Function 2 - np.split

This function is used to divide the array into sub-arrays.

In [19]:
# Example 1 - working
n=np.arange(24)
np.split(n,6)

[array([0, 1, 2, 3]),
 array([4, 5, 6, 7]),
 array([ 8,  9, 10, 11]),
 array([12, 13, 14, 15]),
 array([16, 17, 18, 19]),
 array([20, 21, 22, 23])]

In this example there are 24 array values taken as an input which is split into 6 sub-arrays, that make array to divide into 6*4 shape.

In [20]:
# Example 2 - working
np.split(n,[5,8,17,22])

[array([0, 1, 2, 3, 4]),
 array([5, 6, 7]),
 array([ 8,  9, 10, 11, 12, 13, 14, 15, 16]),
 array([17, 18, 19, 20, 21]),
 array([22, 23])]

In this example it is shown that after taking the input how can we split that into sub-arrays, so that the  sub-arrays will start with certain given values. Here the input is given as 5,8,17,22 respectively , so as a output the sub-arrays also start with those values.

In [22]:
# Example 3 - breaking (to illustrate when it breaks)
np.split(n,5)

ValueError: array split does not result in an equal division

To split the arrays into sub-arrays, array value count must be divided by sub-array value count (i.e, 24%6==0). But in other case it will show error. (i.e, 24%5!=0)

In [ ]:
jovian.commit()

<IPython.core.display.Javascript object>

## Function 3 - np.transpose

This function is used to Reverse the axes of an array and returns the modified array.

In [24]:
# Example 1 - working
x1=np.arange(6)
y1=np.split(x1,2)
y1

[array([0, 1, 2]), array([3, 4, 5])]

In [25]:
y2=np.transpose(y1)
y2

array([[0, 3],
       [1, 4],
       [2, 5]])

In this example at first with 'arange' function we make an array consist of 6 values,then with the help of 'split' function we divided the array into 3x2 shape. At-last with the help of 'transpose' function we reverse the axis to change it to 2x3 shape.

In [10]:
# Example 2 - working
x3 = np.ones((5,4))
x2 = np.ones((4,5))
x2 == x3.T

array([[ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True]])

In this example we compare between two arrays with the transpose function which can be denoted as 'T'.

In [7]:
# Example 3 - breaking (to illustrate when it breaks)
x4 = [[1, 2, 3], 
      [4, 5, 6]]

x4.T

AttributeError: 'list' object has no attribute 'T'

As we know 'transpose' or any numpy functions can only be executed in case of arrays but here the input given as x4 is not an array , its a list and numpy function is not applicable in case of lists, so due to this the example shows an error.

In [11]:
jovian.commit()

<IPython.core.display.Javascript object>

[jovian] Updating notebook "saptaswabasu00/numpy-array-operations" on https://jovian.ai
[jovian] Committed successfully! https://jovian.ai/saptaswabasu00/numpy-array-operations


'https://jovian.ai/saptaswabasu00/numpy-array-operations'

## Function 4 - np.unique

Find the unique elements and returns the sorted unique elements of an array.

In [33]:
# Example 1 - working
a = np.array([[1, 1], [2, 3]])
np.unique(a)

array([1, 2, 3])

In this example we used a simple array to extract the unique value among them,as here 3 value among 4 which are unique.

In [43]:
# Example 2 - working
a = np.array([1, 8, 6, 4, 2, 1, 2, 1])
values, counts = np.unique(a, return_counts=True)
values

array([1, 2, 4, 6, 8])

In [44]:
counts

array([3, 2, 1, 1, 1])

In [45]:
np.repeat(values, counts)

array([1, 1, 1, 2, 2, 4, 6, 8])

In this example, first it extract the unique values, then it print the counts i.e how many times the value is mentioned(also known as frequency).After that the 'repeat' function is used to organize or sort the values.

In [12]:
# Example 3 - breaking (to illustrate when it breaks)
a = np.array([1, 8, 6, 4, 2, 1, 2, 1])
values, counts = np.unique(a,return_counts=False)
np.repeat(values, counts)

ValueError: too many values to unpack (expected 2)

In this example we used the return_counts parameter, which is boolean.If its True, it'll return the number of times each unique item appears in array.As its denoted as false, so at the time of output printing the count function doesn't contain any value thus it gives an error,if we change it to true then it will give right results.

In [13]:
jovian.commit()

<IPython.core.display.Javascript object>

[jovian] Updating notebook "saptaswabasu00/numpy-array-operations" on https://jovian.ai
[jovian] Committed successfully! https://jovian.ai/saptaswabasu00/numpy-array-operations


'https://jovian.ai/saptaswabasu00/numpy-array-operations'

## Function 5 - np.extract

This function is used to extract or return the elements of an array that satisfy some condition.

In [69]:
# Example 1 - working
arr = np.arange(9).reshape((3, 3))
arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [72]:
condition = np.mod(arr, 3)==0
condition

array([[ True, False, False],
       [ True, False, False],
       [ True, False, False]])

In [73]:
np.extract(condition, arr)

array([0, 3, 6])

In this example, firstly we create an array with 3*3 shape.Then we put a condition to check 
which array values is divided by 3 or not, those will return true and others returns the value as false.Now with the help of 'extract' function we print the values which justify the condition.

In [74]:
# Example 2 - working
arr = np.arange(16).reshape((4, 4))
condition = np.mod(arr, 5)==0
np.extract(condition, arr)

array([ 0,  5, 10, 15])

In this example, we almost perform the same operation but with different values.Here we have taken an array from 0 to 15 and between them only 4 value justify the condition which was to print values those are divided by 5 and we got results 0,5,10,15 respectively.

In [15]:
# Example 3 - breaking (to illustrate when it breaks)
arr = np.arange(12).reshape((3, 3))
condition = np.mod(arr, 4)==0
np.extract(condition, arr)

ValueError: cannot reshape array of size 12 into shape (3,3)

In this experiment, the error is due to the reshaping of the array. Here we create a 12 digit array which can be reshaped either 3x4 or 4x3 shape,these two way we can get the right value.But as we reshaped it as 3x3 it gives us an error.

In [ ]:
jovian.commit()

<IPython.core.display.Javascript object>

## Conclusion

Numpy is one of the most versatile and fundamental library in the area of data science specially in python, that helps to reduce various complex problems in one go. Also the utilization of those functions helps to build a unique thought process that helps further to implement these in various other activities.

In [ ]:
jovian.commit()

<IPython.core.display.Javascript object>